# Generated by Django 6.0.3 on 2026-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ready_to_publish',
            field=models.BooleanField(default=False, help_text='Mark as ready for auto-publishing'),
        ),
    ]
