# Generated by Django 6.0.3 on 2026-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_ready_to_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='real_time_minutes',
            new_name='read_time_minutes',
        ),
        migrations.AlterField(
            model_name='article',
            name='required_tier',
            field=models.CharField(choices=[('free', 'Free - Everyone can read'), ('premium', 'Premium - Premium and Pro subscribers'), ('pro', 'Pro - Pro subscribers only')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
