# Generated by Django 6.0.3 on 2026-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_real_time_minutes_article_read_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
