# Generated by Django 6.0.3 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_external_id_article_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
