# Generated by Django 6.0.3 on 2026-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_external_id_alter_article_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
    ]
