# Generated by Django 6.0.3 on 2026-04-24 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_articles_per_month',
            field=models.IntegerField(default=3, help_text='Number of articles per month for free tier users'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='articles_viewed_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
