# Generated by Django 6.0.3 on 2026-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_free_articles_per_month_plan_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiration_reminder_sent',
            field=models.BooleanField(default=True),
        ),
    ]
